const LISTA_PALABRAS = [
  { palabra: "adventure", traduccion: "aventura" },
  { palabra: "ambulance", traduccion: "ambulancia" },
  { palabra: "animal", traduccion: "animal" },
  { palabra: "backpack", traduccion: "mochila" },
  { palabra: "bakery", traduccion: "panadería" },
  { palabra: "banana", traduccion: "plátano" },
  { palabra: "beautiful", traduccion: "hermoso / hermosa" },
  { palabra: "beach", traduccion: "playa" },
  { palabra: "binoculars", traduccion: "binoculares" },
  { palabra: "blanket", traduccion: "manta" },
  { palabra: "bottle", traduccion: "botella" },
  { palabra: "butterfly", traduccion: "mariposa" },
  { palabra: "calendar", traduccion: "calendario" },
  { palabra: "camera", traduccion: "cámara" },
  { palabra: "candy", traduccion: "caramelo" },
  { palabra: "carrot", traduccion: "zanahoria" },
  { palabra: "castle", traduccion: "castillo" },
  { palabra: "chocolate", traduccion: "chocolate" },
  { palabra: "cousin", traduccion: "primo / prima" },
  { palabra: "crayon", traduccion: "crayón" },
  { palabra: "cucumber", traduccion: "pepino" },
  { palabra: "dangerous", traduccion: "peligroso" },
  { palabra: "diamond", traduccion: "diamante" },
  { palabra: "dinosaur", traduccion: "dinosaurio" },

  { palabra: "dolphin", traduccion: "delfín" },
  { palabra: "elevator", traduccion: "ascensor" },
  { palabra: "elephant", traduccion: "elefante" },
  { palabra: "family", traduccion: "familia" },
  { palabra: "feather", traduccion: "pluma" },
  { palabra: "firefighter", traduccion: "bombero" },
  { palabra: "forest", traduccion: "bosque" },
  { palabra: "friendship", traduccion: "amistad" },
  { palabra: "furniture", traduccion: "muebles" },
  { palabra: "garden", traduccion: "jardín" },
  { palabra: "geography", traduccion: "geografía" },
  { palabra: "giraffe", traduccion: "jirafa" },
  { palabra: "glasses", traduccion: "gafas" },
  { palabra: "hamster", traduccion: "hámster" },
  { palabra: "helicopter", traduccion: "helicóptero" },
  { palabra: "holiday", traduccion: "vacaciones" },
  { palabra: "hospital", traduccion: "hospital" },
  { palabra: "island", traduccion: "isla" },
  { palabra: "jacket", traduccion: "chaqueta" },
  { palabra: "jellyfish", traduccion: "medusa" },
  { palabra: "kangaroo", traduccion: "canguro" },
  { palabra: "kitchen", traduccion: "cocina" },
  { palabra: "lighthouse", traduccion: "faro" },

  { palabra: "magician", traduccion: "mago" },
  { palabra: "market", traduccion: "mercado" },
  { palabra: "mirror", traduccion: "espejo" },
  { palabra: "mountain", traduccion: "montaña" },
  { palabra: "museum", traduccion: "museo" },
  { palabra: "necklace", traduccion: "collar" },
  { palabra: "newspaper", traduccion: "periódico" },
  { palabra: "octopus", traduccion: "pulpo" },
  { palabra: "orchestra", traduccion: "orquesta" },
  { palabra: "parrot", traduccion: "loro" },
  { palabra: "passenger", traduccion: "pasajero" },
  { palabra: "pharmacy", traduccion: "farmacia" },
  { palabra: "playground", traduccion: "patio de juegos" },
  { palabra: "rainbow", traduccion: "arcoíris" },
  { palabra: "restaurant", traduccion: "restaurante" },
  { palabra: "sandwich", traduccion: "sándwich" },
  { palabra: "scissors", traduccion: "tijeras" },
  { palabra: "stadium", traduccion: "estadio" },
  { palabra: "strawberry", traduccion: "fresa" },
  { palabra: "sunflower", traduccion: "girasol" },
  { palabra: "thermometer", traduccion: "termómetro" },
  { palabra: "turtle", traduccion: "tortuga" },
  { palabra: "waterfall", traduccion: "cascada" }
];