const LISTA_PALABRAS = [
  { palabra: "apple", traduccion: "manzana" },
  { palabra: "bag", traduccion: "bolsa" },
  { palabra: "birthday", traduccion: "cumpleaños" },
  { palabra: "book", traduccion: "libro" },
  { palabra: "breakfast", traduccion: "desayuno" },
  { palabra: "brother", traduccion: "hermano" },
  { palabra: "cake", traduccion: "pastel" },
  { palabra: "cat", traduccion: "gato" },
  { palabra: "chair", traduccion: "silla" },
  { palabra: "chicken", traduccion: "pollo" },
  { palabra: "classroom", traduccion: "salón de clases" },
  { palabra: "cloud", traduccion: "nube" },
  { palabra: "desk", traduccion: "escritorio" },
  { palabra: "dog", traduccion: "perro" },
  { palabra: "door", traduccion: "puerta" },
  { palabra: "duck", traduccion: "pato" },
  { palabra: "egg", traduccion: "huevo" },

  { palabra: "family", traduccion: "familia" },
  { palabra: "favorite", traduccion: "favorito" },
  { palabra: "fish", traduccion: "pez" },
  { palabra: "flower", traduccion: "flor" },
  { palabra: "frog", traduccion: "rana" },
  { palabra: "garden", traduccion: "jardín" },
  { palabra: "gift", traduccion: "regalo" },
  { palabra: "goat", traduccion: "cabra" },
  { palabra: "grass", traduccion: "césped" },
  { palabra: "green", traduccion: "verde" },
  { palabra: "hand", traduccion: "mano" },
  { palabra: "happy", traduccion: "feliz" },
  { palabra: "hat", traduccion: "sombrero" },
  { palabra: "house", traduccion: "casa" },
  { palabra: "ice", traduccion: "hielo" },
  { palabra: "jam", traduccion: "mermelada" },
  { palabra: "juice", traduccion: "jugo" },

  { palabra: "kite", traduccion: "cometa" },
  { palabra: "lion", traduccion: "león" },
  { palabra: "milk", traduccion: "leche" },
  { palabra: "moon", traduccion: "luna" },
  { palabra: "mouse", traduccion: "ratón" },
  { palabra: "owl", traduccion: "búho" },
  { palabra: "pencil", traduccion: "lápiz" },
  { palabra: "picture", traduccion: "imagen" },
  { palabra: "playground", traduccion: "patio de juegos" },
  { palabra: "rabbit", traduccion: "conejo" },
  { palabra: "rainbow", traduccion: "arcoíris" },
  { palabra: "school", traduccion: "escuela" },
  { palabra: "shoulder", traduccion: "hombro" },
  { palabra: "sister", traduccion: "hermana" },
  { palabra: "teacher", traduccion: "profesor / profesora" },
  { palabra: "weather", traduccion: "clima" }
];